src/main/groovy/liquibase/sdk/test/ChangeObjectTests.groovy
src/main/groovy/liquibase/sdk/test/config/TestConfig.groovy

for some DBs, like cloud ones, we don't really now what version is on server.
Added support for case when DB version is not provided in yaml file, we get it from DB connection.

[no-jira] fixed case when DB version is not provided

---

src/main/groovy/liquibase/harness/config/TestConfig.groovy

Lookup was failing on java 11+
This fix makes the cassandra tests pass on 11 and 16

Correctly lookup test-harness using static-compatible code

---

src/main/resources/liquibase/harness/change/expectedSnapshot/createTableTimestamp.json

This is a very minor addition to the expected results snapshot file for createTableTimestamp. This way, we validate that not only does the column exists, but that it is of the correct datatype.

createTableTimestamp: Add column type to snapshot validation.

---

.github/workflows/main.yml
src/main/resources/liquibase/harness/change/expectedSnapshot/mssql/createTableTimestamp.json
src/test/resources/docker/mysql-init.sql

Removed additional priviliges granting for mysql-init.sql because it somehow breaks permissions for docker container.
Fixed wrong expected snapshot for createTableTimestamp test for mssql

[DAT-7066] Removed -Dmaven.test.failure.ignore=true for mariadb, mysql.

---

src/main/resources/liquibase/harness/change/expectedSnapshot/mssql/createTableTimestamp.json
src/main/resources/liquibase/harness/change/expectedSql/mssql/createTableTimestamp.sql

because of [this]( https://github.com/liquibase/liquibase/pull/1679) change in core had to update expected sql

fixed mssql createTableTimestamp test

---

.github/workflows/aws.yml
src/test/resources/terraform/oracle.tf

AWS has deprecated Oracle RDS 12.2
Test Run here: https://github.com/liquibase/liquibase-test-harness/actions/runs/1884176826

DAT-9484 remove support for Oracle RDS 12.2 due to vendor deprecation

---

src/main/groovy/liquibase/harness/base/BaseLevelTest.groovy
src/main/groovy/liquibase/harness/data/ChangeDataTests.groovy
src/main/groovy/liquibase/harness/util/JSONUtils.groovy
src/main/resources/liquibase/harness/data/changelogs/h2/loadData.datatypes.datetime.csv
src/main/resources/liquibase/harness/data/changelogs/h2/loadData.datatypes.datetime.xml
src/main/resources/liquibase/harness/data/checkingSql/h2/loadData.datatypes.datetime.sql
src/main/resources/liquibase/harness/data/expectedResultSet/h2/loadData.datatypes.datetime.json

[Liquibase PR](https://github.com/liquibase/liquibase/pull/2387)
[Liquibase Issue](https://github.com/liquibase/liquibase/issues/2383)
**Items of Note**
* The SQL in this test uses the `now()` function native to each database.
* This means that each time you run the test, the expected SQL will be different because `now` is never the same twice.
* I had to change the JSONCompareMode to LENIAT in JSONUtils.groovy; without this change, the test cannot pass.
* If this is an unacceptable change, let me know. I can either close the pull request or revise according to your feedback.
This cannot be merged until the next release of Liquibase!

PR-2387: Test to validate datetime handling in loadData.

---

src/main/groovy/liquibase/harness/change/ChangeObjectTests.groovy
src/main/groovy/liquibase/harness/data/ChangeDataTests.groovy

with `assert false`  reason why tests failed isn't shown in the bottom of the log. That makes it harder to quickly figure out reason why build failed. Fixed that

[no-jira] Tests report fix

---

.github/workflows/aws.yml
src/test/resources/aws/postgres.tf

AWS deprecated RDS Postgres 9.6.  Also added platform support for RDS Postgres 14.  All tests passing:
https://github.com/liquibase/liquibase-test-harness/actions/runs/2456101754

DAT-10559 deprecate postgres rds 9.6 and add support for 14

---

src/main/resources/liquibase/harness/change/changelogs/postgresql/addForeignKeyNoValidate.xml
src/main/resources/liquibase/harness/change/expectedSnapshot/postgresql/addForeignKeyNoValidate.json
src/main/resources/liquibase/harness/change/expectedSql/postgresql/addForeignKeyNoValidate.sql

PostgreSQL has implemented a feature, since version 9.1, that ensures that constraints are only checked for new or modified rows, but not for existing data. When defining a constraint, NOT VALID can be added at the end to make use of this feature. A similar feature is available in Oracle under the name of ENABLE NOVALIDATE. Currently, NOT VALID is only allowed for foreign key and check constraints.
Added test for liquibase/liquibase#2600

Added check for validate=false on addForeignKeyConstraint for Postgresql

---

src/main/resources/liquibase/harness/change/changelogs/postgresql/addForeignKeyNoValidate.xml
src/main/resources/liquibase/harness/change/expectedSnapshot/postgresql/addForeignKeyNoValidate.json
src/main/resources/liquibase/harness/change/expectedSql/postgresql/addForeignKeyNoValidate.sql

recreated @nvoxland PR https://github.com/liquibase/liquibase-test-harness/pull/240 as it was mistakenly merged before core changes are merged
PostgreSQL has implemented a feature, since version 9.1, that ensures that constraints are only checked for new or modified rows, but not for existing data. When defining a constraint, NOT VALID can be added at the end to make use of this feature. A similar feature is available in Oracle under the name of ENABLE NOVALIDATE. Currently, NOT VALID is only allowed for foreign key and check constraints.
Added test for liquibase/liquibase#2600

Added check for validate=false on postgresql

---

.github/workflows/main.yml

The current logic works for PRs that are made to test new/changing liquibase functionality, but if a PR is based off `main` it will only consistently pass if it's being ran against a release build. 
For example, if we are adding a new platform for testing, but starting from `main` vs `develop`.
This changes the logic so we also take the target branch of the PR into account in deciding what version of liquibase to run

Don't use snapshots if the target branch for a PR is main

---

.github/workflows/snowflake.yml

job intermittently failing due to "unknown username or password" and I believe it's because the sed command was not escaping chars correctly.  Single quoting should fix.

fix intermittent failure to do invalid user/pass

---

src/main/resources/liquibase/harness/change/changelogs/mariadb/addAutoIncrement.xml
src/main/resources/liquibase/harness/change/changelogs/mysql/addAutoIncrement.xml
src/main/resources/liquibase/harness/change/changelogs/percona-xtradb-cluster/addAutoIncrement.xml

Test updates for liquibase/liquibase#3026

Mysql and friends do not support incrementBy on addAutoIncrement

---

.github/util/workflow-helper.js

Scheduled build can't determine current branch so it uses Liquibase snapshot instead of released version of Liquibase.
This PR has to be merged to main as scheduled builds run only run on default branch 
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
and issue reproducers only for scheduled builds

log payload to help determine issue with scheduled build

---

src/test/resources/harness-config-snowflake.yml
src/test/resources/snowflake/snowflake.tf

LBCAT is getting created by some other manual or automated process in snowflake.  Changing name to something test-harness specific.

use unique test-harness database name instead of lbcat due to conflicts

---

src/main/resources/liquibase/harness/change/expectedSql/mssql/dropColumn.sql

Complicated query is required to drop constraints related to column. Looking a bit weird, but not breaking dropColumn logic.
Also checked SQL server on AWS - https://github.com/liquibase/liquibase-test-harness/actions/runs/3144653155/jobs/5110950175 works there as well

[no-jira] unignored dropColumn for mssql

---

.github/workflows/aws.yml
.github/workflows/azure.yml
.github/workflows/snowflake.yml

Build with evidence that dropAll is executed successfully before each DB has started: https://github.com/liquibase/liquibase-test-harness/actions/runs/3393724992

DAT-12267. added usage of dropAll command to cleanup cloud databases before running the test suite

---

src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/10.2/createFunction.json
src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/10.2/createPackage.json
src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/10.2/createPackageBody.json
src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/10.5/createFunction.json
src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/10.5/createPackage.json
src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/10.5/createPackageBody.json
src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/10.6/createFunction.json
src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/10.6/createPackage.json
src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/10.6/createPackageBody.json
src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/10.7/createFunction.json
src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/10.7/createPackage.json
src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/10.7/createPackageBody.json
src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/createFunction.json
src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/createPackage.json
src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/createPackageBody.json

Mariadb is adding the collate by default when exporting function bodys  as per fix https://jira.mariadb.org/browse/MDEV-29446 . Changes tests to work accordly.

Fix mariadb default collate upstream changes 

---

.github/workflows/aws.yml
src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/10.6/createFunction.json
src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/10.7/createFunction.json
src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/aws_10.6/createFunction.json
src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/aws_10.6/createPackage.json
src/main/resources/liquibase/harness/change/expectedSnapshot/mariadb/aws_10.6/createPackageBody.json
src/test/resources/harness-config-cloud.yml

1. Now `steps.setup.outputs.databaseVersion` is used instead of `matrix.version` in aws.yml  for Oracle and Postgres.
2. Created aws_10.6 directory with test data for AWS MariaDB runs. 
green aws builds are here: 
https://github.com/liquibase/liquibase-test-harness/actions/runs/3489252293
https://github.com/liquibase/liquibase-test-harness/actions/runs/3489979917

Fixed aws builds.

---

src/main/resources/liquibase/harness/change/expectedSql/oracle/19/modifySql.sql

AWS build fails because of Oracle 19 modifySql testcase fails with expectedSQL=
``` /* prepend comment */ CREATE TABLE "C##LIQUIBASE".test_table (test_id INTEGER NOT NULL, test_column VARCHAR2(50) NOT NULL) -- append comment``` but should be 
```/* prepend comment */ CREATE TABLE LBUSER.test_table (test_id INTEGER NOT NULL, test_column VARCHAR2(50) NOT NULL) -- append comment```
as for AWS we have different user than for regular Oracle workflow run

[no-jira] override modifySql changelog for Oracle 19 on AWS

---

src/main/resources/liquibase/harness/change/changelogs/snowflake/createFunction.xml
src/main/resources/liquibase/harness/change/changelogs/snowflake/dropFunction.xml

They are automatically added by generateSql method
Snowflake Cloud workflow is passed - https://github.com/liquibase/liquibase-test-harness/actions/runs/4023232260

DAT-13155 Remove unnecessary parentheses from dropFunction Change Type

---

src/main/resources/liquibase/harness/change/expectedSnapshot/snowflake/createTableDataTypeDoubleIsFloat.json

In order to createTableDataTypeDoubleIsFloat testcase work with latest core changes expected "typeName" should be "DOUBLE"

[no-jira] Snowflake createTableDataTypeDoubleIsFloat testcase fix

---

src/main/resources/liquibase/harness/change/expectedSql/db2-luw/addDefaultValueBoolean.sql

This change is required since `supportsBooleanDataType()` has been updated in this [PR](https://github.com/liquibase/liquibase/pull/4754).

addDefaultValueBoolean expected sql updated

---

.github/util/workflow-helper.js

fix: `.github/util/workflow-helper.js` : the finish step in DAT-16486 is looking at the old `build.yml` file. We need to make sure it takes the run of the new workflow and not the old `build.yml`
Error link : https://github.com/liquibase/liquibase-test-harness/actions/runs/7290781935/job/19868497916#step:4:109

DAT-16486: use run-tests.yml from OSS workflow

---

README.md

When using Windows and Maven, all command line properties with the format `-Dsomething.another=value` must be written with double quotes: `-D"something.another"=value`

Update README.md to include Windows syntax

---

.github/workflows/azure.yml

fix(azure.yml): remove 'postgresql:azure' from default databases list… as it is not supported
feat(azure.yml): update job to add support for flexible PostgreSQL server testing
feat(azure.yml): update job to dynamically select PostgreSQL version for testing

DAT-17032-17033 Setup Azure Postgres 15/16

---

.github/workflows/attach-artifact-release.yml
.github/workflows/create-release.yml
.github/workflows/release-published.yml

feat: `.github/workflows/create-release.yml`: use `liquibase/build-logic/.github/workflows/create-release.yml` to run Release Drafter to auto create draft release notes
feat: `.github/workflows/release-published.yml`: use `liquibase/build-logic/.github/workflows/extension-release-published.yml` to Publishe a release to Maven Central
feat: `.github/workflows/attach-artifact-release.yml`: use `liquibase/build-logic/.github/workflows/extension-attach-artifact-release.yml` to attaches a tested artifact to the draft release.

DAT-17264: use build-logic reusable workflow

---

pom.xml

As discussed with the team on [Slack](https://liquibase.slack.com/archives/CK9JJEENB/p1712845031776109), we should keep alignment on driver versions across the projects and not use `preview` versions. So reverting this version upgrade to the previous version.

Downgrade MSSQL driver version from 12.7.0.jre11-preview to 12.6.1.jre11

---

.github/workflows/main.yml

fix: `.github/workflows/main.yml`: we are sending notification at the very end on the Finish job which triggers exactly the same job. 
Removing the previous step which is sending the notification as @user

DAT-17492: remove user status check

---

.github/workflows/aws-weekly.yml

✨ (aws-weekly.yml): Add AWS Weekly Cloud Database Test Execution workflow for testing Cloud Databases with test-harness using Terraform Action
🔧 (aws-weekly.yml): Configure workflow to run every Sunday at 6:00 AM and allow manual triggers with specified test classes and databases to start up
🚀 (aws-weekly.yml): Implement jobs for setup, deploying ephemeral cloud infrastructure, initializing MySQL databases, and running tests on various database platforms and versions
✨ Add support for running tests on different database platforms and versions using Maven 🔧 Update test run configurations to include database platform, version, username, password, and URL 🔧 Add support for running tests on AWS Aurora database platform 🔧 Include logic to archive test results for AWS RDS databases 🔧 Implement …

DAT-17834 Ephemeral AWS infra for liquibase-test-harness

---

.github/workflows/attach-artifact-release.yml
.github/workflows/create-release.yml
.github/workflows/release-published.yml

🔧 (.github/workflows): update workflow file references to use the 'main' branch instead of specific version tags
🔧 (.github/workflows/create-release.yml): add configuration to disable Sonar analysis during release creation

DAT-18326 test-harness is failing at createRelease step

---

.github/workflows/main.yml

fix: `.github/workflows/main.yml`: This ensures that the BOT_TOKEN has the necessary access for the actions you want to perform.Sometimes, even with a PAT, GitHub might restrict actions for security.
successful run for a dependabot PR :
PR: https://github.com/liquibase/liquibase-test-harness/pull/884
run: https://github.com/liquibase/liquibase-test-harness/actions/runs/10621496852/job/29443823445?pr=884

🔧 DAT-18287: fix `Bad credentials`

---

.github/workflows/main.yml

- fix: `.github/workflows/main.yml` :this will grant the workflow the ability to write contents to the repository and also set commit statuses, which is what the github.rest.repos.createCommitStatus API call does.

🔧 DAT-18287 statuses: write

---

pom.xml

For open-source repos, like test-harness we don't need to hide javadocs or sources. Vice versa, sources need to be public to conveniently work with test-harness tests in extensions.

[DAT-18732] fixed sources and javadoc jars

---

src/main/groovy/liquibase/harness/compatibility/foundational/FoundationalTest.groovy

This PR substitutes https://github.com/liquibase/liquibase-test-harness/pull/937 as PRs outside of Liquibase org don't get secrets and can't run successfully

[no-jira] brought @vladimirevd fix

---

src/test/resources/init-changelogs/gcp/mssql.sql

If this will not help, need to test adding LIQUIBASE_LIQUIBASE_SCHEMA_NAME to env var for gcp_mssql
https://github.com/liquibase/liquibase-test-harness/actions/runs/12394911484/job/34599452458 tests passed

[DAT-18428] GCP MSSQL :: SPIKE: determine why test-harness tests for GCP MSSQL are periodically failing during the  drop-all command execution.

---

pom.xml
src/main/groovy/liquibase/harness/generateChangelog/GenerateChangelogTest.groovy

The system was encountering a `/null` path issue when attempting to locate the createTable.sql file, affecting the test reliability.
- Modified the cleanup mechanism in `GenerateChangelogTest` to correctly target and remove generated files in the `src/test/resources/generated/` directory
- Implemented a pre-test cleanup routine to ensure a clean state before test execution
- Fixed the path resolution logic for SQL file lookup
The test execution now shows successful cleanup operations:

DAT-18731 - Resolving the /null problem when not finding the createTable.sql

---

.github/workflows/deploy-snapshot.yml
pom.xml

This pull request introduces a new GitHub Actions workflow for deploying master snapshots and updates the Maven configuration to use GitHub Packages instead of Sonatype Nexus. The most important changes are summarized below:
* [`.github/workflows/deploy-snapshot.yml`](diffhunk://#diff-90d663ded563f94b4a2d1759ad49ac0408ad22970424654ebe25494646a9d364R1-R32): Added a new workflow named "Deploy Master Snapshot" that triggers on pushes to the `main` branch. This workflow checks out the code, sets up JDK 17, updates the version to `master-SNAPSHOT`, and builds and deploys the snapshot to GitHub Packages.
* [`pom.xml`](diffhunk://#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8L461-R468): Updated the `distributionManagement` section to replace Sonatype Nexus repositories …

DAT-19350   configure test-harness to deploy master-snapshot to GPM

---

src/test/resources/docker/docker-compose.yml
src/test/resources/docker/tidb-init.sql

This pull request includes changes to the `docker-compose.yml` file in `src/test/resources/docker` to update the version format, correct inconsistencies, and add new services.
Key changes include:
* **Version format update:**
- Changed the version format from single quotes to double quotes (`version: "3.3"`).
* **Service configuration adjustments:**
- Corrected the format of the `LICENSE` environment variable in the `db2-luw` service.
* **Addition of new services:**
- Added a new service `ti-db` with the `pingcap/tidb` image, including configuration for ports and volumes.
- Added a new service `ti-db-mysql` with the `mysql:latest` image, including dependency on `ti-db`, initialization script, and network mode settings.

DAT-19303 DevOps :: TiDB :: Add ability to run custom SQL script that creates tables and table data against created db

---

.github/workflows/snowflake.yml

As we are using in snowflake flow URL directly ad a maven tag `DdbUrl` we could update URL with decoded and saved in a tmp location private key right away in the `Snowflake Test Run`  step

DAT-19863 add PKI authentication by default for snowflake test harness flows.

---

.github/workflows/aws.yml
README.localstack.md

This pull request updates the authentication mechanism for LocalStack by replacing the use of `LOCALSTACK_API_KEY` with `LOCALSTACK_OAUTH_TOKEN` in both the GitHub Actions workflow and the documentation. 
* [`.github/workflows/aws.yml`](diffhunk://#diff-30da5423bd49b3f1dfdb92f40038a27f5747f4b8af0ed81ca3a8e2691be18e69L72-R72): Replaced `LOCALSTACK_API_KEY` with `LOCALSTACK_OAUTH_TOKEN` in the environment variables for the "Start & Configure LocalStack" job.
* [`README.localstack.md`](diffhunk://#diff-1cc81e856cf09df88220f57179c3345afc776a452783897f167ffff43ab7e769L19-R19): Updated the example command to export `LOCALSTACK_OAUTH_TOKEN` instead of `LOCALSTACK_API_KEY` in the LocalStack setup instructions.

DAT-20080 DevOps :: Migrate legacy LocalStack API keys to new Auth Tokens

---

.github/workflows/main.yml

This pull request updates the GitHub Actions workflow configuration in `.github/workflows/main.yml` to enhance security and streamline token management. The most important changes involve replacing hardcoded personal access tokens (PATs) with dynamically generated GitHub App tokens and updating permissions for better access control.
* Updated the `Setup` job to include explicit permissions (`contents: write` and `packages: read`) for better access control.
* Replaced hardcoded `LIQUIBOT_PAT` secrets with the dynamically generated `${{ secrets.GITHUB_TOKEN }}` for authentication in the workflow.
* Added a new step to generate a GitHub App token using the `actions/create-github-app-token@v1` action. This step retrieves the token using the app's ID and private key, ensuring secure and …

DAT-20178: use GITHUB_TOKEN and GitHub App token for creating status

---

.github/workflows/advanced.yml
.github/workflows/aws.yml

This pull request updates GitHub Actions workflows to improve security and streamline token usage. The most significant changes include replacing generic tokens with more specific ones, introducing a GitHub App token, and reformatting the default database list for better readability.
* Replaced `BOT_TOKEN` with `LIQUIBOT_PAT_GPM_ACCESS` for improved token specificity in multiple steps across `.github/workflows/advanced.yml` and `.github/workflows/aws.yml`. [[1]](diffhunk://#diff-92e6e09976406d5c12da9490bac6dc147bb1c217e688025ed0e3f949b8e71aecL65-R66) [[2]](diffhunk://#diff-92e6e09976406d5c12da9490bac6dc147bb1c217e688025ed0e3f949b8e71aecL143-R156) [[3]](diffhunk://#diff-30da5423bd49b3f1dfdb92f40038a27f5747f4b8af0ed81ca3a8e2691be18e69L73-R73)
* Introduced the use of a GitHub App token by …

DAT-20178: use LIQUIBOT_PAT_GPM_ACCESS instead of a BOT_TOKEN

---

.github/workflows/main.yml

This pull request updates the GitHub Actions workflow to use a newer version of the `actions/create-github-app-token` action.
* [`.github/workflows/main.yml`](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3L345-R345): Updated the `uses` field for the `Get GitHub App token` step to use version `v2` of the `actions/create-github-app-token` action instead of `v1`.

🔧 uses: actions/create-github-app-token@v2

---

.github/workflows/aws.yml

This pull request updates the `.github/workflows/aws.yml` file to adjust the startup command for LocalStack. The change ensures that the `MSSQL_ACCEPT_EULA` environment variable is explicitly set during the LocalStack startup process.
Workflow configuration updates:
* [`.github/workflows/aws.yml`](diffhunk://#diff-30da5423bd49b3f1dfdb92f40038a27f5747f4b8af0ed81ca3a8e2691be18e69L99-R99): Modified the LocalStack startup command to include `MSSQL_ACCEPT_EULA=Y`, aligning the environment variable setup with the requirements for running the MSSQL server.

DAT-20416 Fix AWS MSSQL 2019 instance for the interop team

---

.github/workflows/snowflake.yml

Successful run : https://github.com/liquibase/liquibase-test-harness/actions/runs/17869259920 
This pull request updates the `.github/workflows/snowflake.yml` workflow to standardize the use of the `LIQUIBASETH` user and its associated private key for Snowflake authentication, and adds comments to clarify the purpose of certain jobs. The changes help improve security, consistency, and maintainability of the workflow.
**Authentication and User Standardization**
* Updated all references to the Snowflake user and private key to use `LIQUIBASETH` and its corresponding environment variable, ensuring consistent authentication throughout the workflow. [[1]](diffhunk://#diff-a10408a8566b2d8ad461fc462897fba9c698ee7d74531e952bc0d51b2f064908L67-R75) …

DAT-20624: use appropriate private key for LIQUIBASETH user
