liquibase/liquibase-test-harness

- src/main/groovy/liquibase/sdk/test/config/TestConfig.groovy
- src/main/groovy/liquibase/sdk/test/util/ChangeObjectTestHelper.groovy
https://datical.atlassian.net/browse/DAT-6103
> fixed filtering

- README.md
- src/test/groovy/liquibase/harness/util/TestUtilsTest.groovy
https://datical.atlassian.net/browse/DAT-6866
> [DAT-6866] fixed TestUtilsTest, updated readme

- src/test/resources/docker/docker-compose.yml
- src/test/resources/harness-config.yml
Well, like it says ^^^^ ....
Ran locally and is identical results to earlier CDB test results.
> Add testing for CockroachDB 21.1.0

- src/test/resources/harness-config.yml
Reverts liquibase/liquibase-test-harness#119
> Revert "DAT-8039 add Oracle RDS Support to test-harness"

- .github/workflows/aws.yml
- src/test/resources/harness-config.yml
- src/test/resources/terraform/changelogs/oracle.sql
- src/test/resources/terraform/oracle.tf
- src/test/resources/terraform/postgres.tf
- src/test/resources/terraform/variables.tf
Reverts liquibase/liquibase-test-harness#118
> Revert "Revert "DAT-8039 add Oracle RDS Support""

- .github/workflows/main.yml
- src/main/resources/liquibase/harness/change/changelogs/mysql/createTableWithRemarks.xml
- src/main/resources/liquibase/harness/change/expectedSnapshot/createTableWithRemarks.json
- src/main/resources/liquibase/harness/change/expectedSql/mariadb/setPrimaryKeyColumnRemarks.sql
- src/test/resources/liquibase/harness/change/expectedSql/mysql/createTableWithRemarks.sql
Test for liquibase/liquibase#2301 where adding remarks to a primary key column removes the primary key definition.
> Test that mysql remarks

- src/main/resources/liquibase/harness/change/expectedSql/sqlite/addAutoIncrement.sql
- src/main/resources/liquibase/harness/change/expectedSql/sqlite/addDefaultValue.sql
- src/main/resources/liquibase/harness/change/expectedSql/sqlite/addDefaultValueBoolean.sql
- src/main/resources/liquibase/harness/change/expectedSql/sqlite/addDefaultValueComputed.sql
- src/main/resources/liquibase/harness/change/expectedSql/sqlite/addDefaultValueDate.sql
- src/main/resources/liquibase/harness/change/expectedSql/sqlite/addDefaultValueNumeric.sql
- src/main/resources/liquibase/harness/change/expectedSql/sqlite/dropColumn.sql
- src/main/resources/liquibase/harness/change/expectedSql/sqlite/mergeColumns.sql
https://github.com/liquibase/liquibase/issues/2644 .
> Ignore changetypes with bug

- pom.xml
recreated https://github.com/liquibase/liquibase-test-harness/pull/229 directly to main.
> [no-jira] updated postgre driver

- src/test/resources/snowflake/snowflake.tf
add CREATE FUNCTION privs to snowflake
> add CREATE FUNCTION permissions for snowflake

- src/main/resources/liquibase/harness/change/changelogs/snowflake/createFunction.xml
- src/main/resources/liquibase/harness/change/changelogs/snowflake/dropFunction.xml
- src/main/resources/liquibase/harness/change/expectedSnapshot/snowflake/createFunction.json
- src/main/resources/liquibase/harness/change/expectedSnapshot/snowflake/dropFunction.json
- src/main/resources/liquibase/harness/change/expectedSql/snowflake/createFunction.sql
- src/main/resources/liquibase/harness/change/expectedSql/snowflake/dropFunction.sql
After 4.12 release that included Snowflake and functions support for it unignored 2 tests
> [no_jira] unignored functions for snowflake

- .github/workflows/main.yml
- pom.xml
Test updates for liquibase/liquibase#3050
> Added liquibase-commercial dependency

- README.md
- src/main/resources/liquibase/harness/change/expectedSnapshot/h2/addDefaultValueSequenceNext.json
- src/main/resources/liquibase/harness/change/expectedSql/h2/addDefaultValueNumeric.sql
- src/main/resources/liquibase/harness/change/expectedSql/h2/addDefaultValueSequenceNext.sql
Test update for liquibase/liquibase#3098
> Update test for change in h2 from "number" to "numeric"

- src/test/resources/docker/docker-compose.yml
add healtcheck to mssql containers
> DAT-11410 add healtcheck to mssql containers

- .github/workflows/OracleRunParallel.yml
- .github/workflows/main.yml
- src/test/resources/docker/create-infra.sh
Updating ubuntu version on GH runner to mitigate this error: `The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest)`
> Update ubuntu version in main.yml

- pom.xml
Manually created upgrade to jdbc-mssql 11.2.0
> Upgrade jdbc-mssql dependency to 11.2.0.jre8

- .github/workflows/azure.yml
run workflow for this PR manually - https://github.com/liquibase/liquibase-test-harness/actions/runs/3298349116/jobs/5440348786
> [no-jira] unignored azure

- pom.xml
> Bump sdk version to 0.10.20

- .github/workflows/main.yml
Hopefully fixes GitHub trigger for oss
> Fix GitHub trigger for oss

- src/test/resources/automation-runner.sh
Reverts liquibase/liquibase-test-harness#395
> Revert "[no-jira] added java argument for HSQL"

- .github/workflows/azure.yml
- src/main/groovy/liquibase/harness/util/SnapshotHelpers.groovy
- src/main/groovy/liquibase/harness/util/TestUtils.groovy
- src/main/resources/liquibase/harness/change/expectedSql/mysql/azure/addCheckConstraint.sql
- src/main/resources/liquibase/harness/change/expectedSql/mysql/azure/createFunction.sql
- src/main/resources/liquibase/harness/change/expectedSql/mysql/azure/createPackage.sql
- src/main/resources/liquibase/harness/change/expectedSql/mysql/azure/createPackageBody.sql
- src/main/resources/liquibase/harness/change/expectedSql/mysql/azure/createProcedure.sql
- src/main/resources/liquibase/harness/change/expectedSql/mysql/azure/createProcedureFromFile.sql
- src/main/resources/liquibase/harness/change/expectedSql/mysql/azure/dropCheckConstraint.sql
- src/main/resources/liquibase/harness/snapshot/expectedSnapshot/column.json
- src/test/resources/harness-config-cloud.yml
- src/test/resources/init-changelogs/azure/mysql.sql
Green build is here: https://github.com/liquibase/liquibase-test-harness/actions/runs/3592671742
> DAT-12500.  added Azure MySQL support to test harness.

- .github/workflows/azure.yml
- src/test/resources/harness-config-cloud.yml
Green build is here: https://github.com/liquibase/liquibase-test-harness/actions/runs/3799717243
> DAT-12793. added postgresql flexible server to azure.yml workflow

- src/main/resources/liquibase/harness/change/expectedSql/mariadb/addDefaultValueComputed.sql
* Updated expected default value for addDefaultValueComputed sql file based on MySQL changes made for functions
Co-authored-by: Daniel Mallorga <dmallorga@liquibase.com>
> merge develop into main after Liquibase release

- src/main/resources/liquibase/harness/change/changelogs/snowflake/createTableDataTypeDoubleIsFloat.xml
- src/main/resources/liquibase/harness/change/expectedSnapshot/snowflake/createTableDataTypeDoubleIsFloat.json
- src/main/resources/liquibase/harness/change/expectedSql/snowflake/createTableDataTypeDoubleIsFloat.sql
Add tests to new type DOUBLE specific for Snowkflake
> Add Snowflake double to float tests.

- src/main/groovy/liquibase/harness/util/DatabaseTestContext.groovy
not all connections are JDBC connections (like MongoConnection), and we need to close them properly as well
> [DAT-13428] fixed explicit class casting

- src/main/resources/liquibase/harness/change/changelogs/snowflake/createProcedure.xml
- src/main/resources/liquibase/harness/change/changelogs/snowflake/createProcedureFromFile.xml
- src/main/resources/liquibase/harness/change/changelogs/snowflake/dropProcedure.xml
triggered workflow manually  https://github.com/liquibase/liquibase-test-harness/actions/runs/4491973659
> [snowflake_cicd_fix] removed empty brackets

- .gitignore
- src/main/resources/liquibase/harness/change/expectedSql/mariadb/sqlFile.sql
- src/main/resources/liquibase/harness/change/expectedSql/oracle/aws_19/modifySql.sql
- src/main/resources/liquibase/harness/data/expectedSql/oracle/aws_19/delete.sql
- src/main/resources/liquibase/harness/data/expectedSql/oracle/aws_19/insert.sql
- src/main/resources/liquibase/harness/data/expectedSql/oracle/aws_19/loadData.sql
- src/main/resources/liquibase/harness/data/expectedSql/oracle/aws_19/loadUpdateData.sql
Build: https://github.com/liquibase/liquibase-test-harness/actions/runs/4510274744
> fixed oracle aws test failures

- src/main/resources/liquibase/harness/change/expectedSql/oracle/19.3.0/sqlFile.sql
- src/main/resources/liquibase/harness/change/expectedSql/oracle/aws_19/sqlFile.sql
- src/main/resources/liquibase/harness/change/expectedSql/oracle/oci/sqlFile.sql
https://github.com/liquibase/liquibase-test-harness/actions/runs/4948253088 Oracle AWS run
https://github.com/liquibase/liquibase-test-harness/actions/runs/4948284530 Oracle OCI build
https://github.com/liquibase/liquibase-test-harness/actions/runs/4948295909 Oracle Parallel Test Execution
> [no-jira] override sqlFile for different oracle instances

- src/main/groovy/liquibase/harness/diff/DiffCommandTest.groovy
- src/main/groovy/liquibase/harness/diff/DiffCommandTestHelper.groovy
Build: https://github.com/liquibase/liquibase-test-harness/actions/runs/5045966353
> DAT-14857. used regex to removed unstable data verification during the diff test

- .github/workflows/aws.yml
- README.md
Build: https://github.com/liquibase/liquibase-test-harness/actions/runs/5253969678
> removed aws postgres 10 from the build matrix due to EOL of instance

- .github/workflows/advanced.yml
- .github/workflows/main.yml
https://datical.atlassian.net/browse/DAT-16328
> DAT-16328 test-harness build fails on setup step

- .github/workflows/main.yml
during the run for refactor logic: I am getting an error `syntax on line 58`. I checked all my code and the only place line 58 is an issue is in this `main.yml` file which states `unexpected end of the stream within a double quoted scalar` which is on line 58.
> fix error unexpected end of the stream within a double quoted scalar

- .github/workflows/main.yml
fix: `.github/workflows/main.yml`: test harness downloads wrong build
> Fix: add liquibase-sdk-maven-plugin attributes

- .github/workflows/main.yml
feat: `.github/workflows/main.yml`: adding oss_workflow_url to show from which OSS PR the run was triggered
> DAT-16455: test-harness Triggered by OSS PR

- .github/workflows/main.yml
feat:`.github/workflows/main.yml`: get Test-Harness info on OSS page
> DAT-16486: get Test-Harness info on OSS page

- .github/workflows/main.yml
fix : `.github/workflows/main.yml` : remove unwanted code
> DAT-16455: remove unwanted code

- src/main/resources/liquibase/harness/change/expectedSql/mariadb/addDefaultValueBoolean.sql
- src/main/resources/liquibase/harness/change/expectedSql/mariadb/addNotNullConstraintBitBoolean.sql
Changes performed to update expected SQL results according to changes made in this OSS [PR](https://github.com/liquibase/liquibase/pull/5522).
> Expected SQL files updated to reflect MariaDB boolean changes from OSS

- src/test/resources/init-changelogs/aws/mariadb.sql
- src/test/resources/init-changelogs/aws/mssql.sql
- src/test/resources/init-changelogs/aws/mysql.sql
- src/test/resources/init-changelogs/aws/postgresql.sql
- src/test/resources/init-changelogs/azure/mysql.sql
- src/test/resources/init-changelogs/azure/postgresql.sql
- src/test/resources/init-changelogs/azure/sqlserver.sql
- src/test/resources/init-changelogs/gcp/mssql.sql
- src/test/resources/init-changelogs/gcp/mysql.sql
- src/test/resources/init-changelogs/snowflake/snowflake.sql
Snowflake: https://github.com/liquibase/liquibase-test-harness/actions/runs/7799351890
GCP: https://github.com/liquibase/liquibase-test-harness/actions/runs/7799347811
Azure: https://github.com/liquibase/liquibase-test-harness/actions/runs/7799346267
AWS: https://github.com/liquibase/liquibase-test-harness/actions/runs/7799338052
> DAT-16820. refactored cloud DBs init-scripts to follow Liquibase atomic changes best practice

- README.md
checked Postegres 16 on AWS Aurora and AWS RDS by running ChangeObjectTests, ChangeDataTests, GenerateChangelogTest and SnapshotObjectTests
> [DAT-16959, DAT-16960] updated support matrix

- .github/workflows/OracleRunParallel.yml
- .github/workflows/advanced.yml
- .github/workflows/main.yml
- src/test/resources/docker/create-infra.sh
- src/test/resources/docker/docker-compose.edb.yml
- src/test/resources/docker/oracle-artifactory/docker-compose.yml
chore(OracleRunParallel.yml): update Docker login credentials to use new repository URL and credentials
chore(advanced.yml, main.yml): update environment variables to use new repository URL and credentials
chore(create-infra.sh): update Docker login command to use new repository URL and credentials
chore(docker-compose.edb.yml): update image URLs to point to new repository URL
chore(oracle-artifactory/docker-compose.yml): update image URL to point to new repository URL
> DAT-17572 Modify CI/CD Configurations for Nexus Integration

- .github/workflows/main.yml
To be fixed in https://datical.atlassian.net/browse/DAT-19185 .
> chore: remove MSSQL 2019 and 2022 from build until they are fixed.

- .gitignore
- src/main/groovy/liquibase/harness/snapshot/SnapshotObjectTestHelper.groovy
- src/main/groovy/liquibase/harness/snapshot/SnapshotObjectTests.groovy
Adding 'invalid test' to expected file skips test case, just like in other tests
> [DAT-18736] added common 'ignore testcase' functionality to Snapshot test

- src/main/resources/liquibase/harness/change/expectedSql/postgresql/addNotNullConstraintBitBoolean.sql
Related to https://github.com/liquibase/liquibase/pull/6695
> Fix for postgres

- src/main/resources/liquibase/harness/change/expectedSql/postgresql/addNotNullConstraintBitBoolean.sql
Reverts liquibase/liquibase-test-harness#990
> Revert "Fix for postgres"

- .github/workflows/snowflake.yml
- src/test/resources/docker/docker-compose.yml
+container_name fix in docker-compose. Docker doesn't like 2 containers with the same name
> [no_jira] snowflake_multiline_fix

- .github/workflows/gcp.yml
Green build: https://github.com/liquibase/liquibase-test-harness/actions/runs/15926299569
> DAT-20353. refactored gcp mssql script to use admin user to execute init script
